dist: xenial
language: node_js
node_js:
  - 10

before_install:
  export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION_MB_DIST}

before_script:
  - npm install -g serverless
  - serverless --version
  - npm install
  - cd dependencies/nodejs && npm install && cd ../..

jobs:
  include:
    - stage: deploy
      name: Milkbox Funnels Distributor to Staging
      if: type = push AND tag =~ ^staging-deploy-.*$
      env:
        - environment=staging
        - googleBucket=mb-funnels-bucket-snth
        - awsBucket=funnel-origin-bucket-snth
        - accessKeyId=${AWS_DEFAULT_REGION_MB_DIST}
        - secretAccessKey=Gu6uk1HpIsBqj3fwxxa6Q4UvIYdW6JAJVNvUF36Y
      script:
        - npm run build
        - sam validate
        - sam package --template-file template.yaml --s3-bucket prod-milkbox-cloudformation-templates --output-template-file out.yaml
        - sam deploy --template-file ./out.yaml --stack-name mb-funnels-distributor-staging --capabilities CAPABILITY_IAM --parameter-overrides Environment=staging
    - stage: deploy
      name: Milkbox Funnels Distributor to Production
      if: type = push AND tag =~ ^deploy-.*$
      env: environment=production
      script:
        - npm run build
        - sam validate
        - sam package --template-file template.yaml --s3-bucket prod-milkbox-cloudformation-templates --output-template-file out.yaml
        - sam deploy --template-file ./out.yaml --stack-name mb-funnels-distributor-production --capabilities CAPABILITY_IAM --parameter-overrides Environment=production